### ISSUE TITLE
Windows version ?

### ISSUE THREAD

**Issue by lilinfr** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#111]
Hi !

Any chance to get a MS windows version ? :)

**Comment by superpoweredSDK** [comment]
We will have it at some point, because Superpowered doesn't have any dependency on the operating system. It can run on everything, however our team is too small yet to provide support for another large platform. 

We have 10 so far, all architectures separately written and optimized:
- iOS (Simulator, 32-bit ARM, 64-bit ARM)
- Mac OSX (X86_64)
- tvOS (Simulator, 64-bit ARM)
- Android (32-bit ARM, 64-bit ARM, X86, X86_64]

Working on it.

**Comment by swan488** [comment]
Another vote for Windows to be support please!!
