### ISSUE TITLE
Z

### ISSUE THREAD

**Issue by Onizuka1117** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#113]
@Guy-kun
 
Guy-kun commented 18 hours ago
I'm currently using the SDK to playback MP3s as background for a music game I'm developing. 
I simply use the AdvancedAudioPlayer to load and play() the mp3 files (which are bundled together with the apk on Android, hoping this gives the best playback performance.

I'm finding however that inconsistently, and more frequently when CPU usage is high due to something like screen recording, audio stutters. When this audio stutter happens it seems that synchronization is lost and playback falls behind the original intended speed/progress so the audio loses sync with what is on-screen.

My question is two things:
1) Is the stuttering under cpu strain usual? I've tested on a variety of fairly powerful devices and this seems to happen rarely (once per 2 plays of an mp3, or ~3-4 times if screen recording) across all of them
2) Is there any way that I can guarantee playback progress remains consistent even if this happens? I can see features related to synchronization but don't really know what's the best approach for this or if it is possible.

**Comment by superpoweredSDK** [comment]
Hello,

no matter if you use Superpowered or any other audio engine, you need to complete audio processing in the audio processing callback, before the buffer size's time elapses. For example, if your buffer size is 128 at 48000 Hz, then you have less than 2.6 ms to complete your audio processing for each "turn".

If your audio is stuttering, then you don't finish with audio processing in time. This can be caused by:

- You are doing too much in the audio processing callback. How many players, effects and other stuff is active?
- You are doing a blocking operation in the audio processing callback, which waits for too long. Such as allocating memory on the heap (malloc, new) or waiting for a mutex to unblock.

Btw, it doesn't matter if you load the files from the apk or other location in the disk.

**Comment by Guy-kun** [comment]
Hey @superpoweredSDK 
The two tickets sure got closed quickly, didn't even get a chance to reply to your question... Also, this issues is the duplicate, not my previous one (this looks almost like it was made by a bot).

Anyway, 
- How many players, effects is active: only one, just a single AdvancedAudioPlayer is active, the callback also does not have any logic other than:

```
if (player->process(stereoBuffer, false, numberOfSamples, playerVolume, 0.0f, -1.0 ))
		{
	        SuperpoweredFloatToShortInt(stereoBuffer, audioIO, numberOfSamples);
	        return true;
	    }
```
I am however using the cocos2dx graphics library for the game which also performs all logic in native code.
Could this possibly interfere with superpowered's audio processing? Does this callback get called on the same thread as all other native code in the application? With the lack of debugging available to NDK code I can't really get to the bottom of what is going on..


Additional to this original issue, I'm experiencing pause failing a lot on my android device, when calling
`pause(0,0);` from either a JNI callback or a EOF callback, the JNI one seems to fail the majority of time (maybe works 1 in 10 times) and the EOF one fail around 1 in 10times.  - In the EOF case I specifically only ever play audio with looping disabled `play(false)` but still find it sometimes loops once more.

Do you know any reasons this could happen or anything I should watch for when trying to pause audio?
Thanks
