### ISSUE TITLE
SuperpoweredAdvancedAudioPlayer reverse looping seems not working

### ISSUE THREAD

**Issue by felart** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#123]
Hi, I can't play a loop continuously in reverse (on iOs).

If reverseToForwardAtLoopStart=true the loop go backward and go forward at the beginning of the loop and loops normally.
But If reverseToForwardAtLoopStart=false the loop go backward and stop at the beginning of the loop and a high sound occurs.

An other problem :if I use seek in reverse mode, seeking works but the loop stop and a high sound occurs too.

Is there something to do to correct this behavior?

Thanks.

**Comment by superpoweredSDK** [comment]
Reverse looping is not supported at all, sorry. The behaviours are correct as you described, except the "high sound". It occurs if you don't handle the player's process() method's return value (silence or not) correctly.

**Comment by felart** [comment]
Bad news, any chance to have this functionality in future? For me it seems to be a common feature but maybe there's a technical reason.
Is there a way to do it manually: seek to end and setreverse each time when we reach the beginning maybe?

Thanks for the information about handling player's process() method's return value.

**Comment by renezuidhof** [comment]
It's been 7 years, so I guess looping in combination with 'setReverse(true)' is not going to be supported?

**Comment by gaborszanto** [comment]
Looping with reverse is supported.

**Comment by renezuidhof** [comment]
I noticed reverse does indeed work when using `loop` or `loopBetween`, but not when using `loopOnEOF` as the looping method.

For my app I need to use `loopOnEOF` because the other two methods I mentioned cause a very slight delay every time it loops. It's like a 1 millisecond delay, but when there's a short clip (let's say 400ms) it will be noticeable after a few minutes of looping.

**Comment by gaborszanto** [comment]
loop and loopBetween doesn't add any delay for loops. If they would, none of the DJ applications using Superpowered would be usable.

**Comment by renezuidhof** [comment]
I've edited the SuperpoweredPlayer example project to show this issue. I've attached the files that I changed in case you want to check it out.

In this example two AdvancedAudioPlayers are opened. One using `loopOnEOF` and the other `loopBetween`. Besides that they are identical.

When I run this for like 5 minutes I hear them drifting apart. At least that is what happens on my device (Xiaomi Poco F2 Pro). As far as I have experienced in my own app it's because the `loopBetween` function adds a tiny delay, I don't even think it's 1 millisecond. But after looping 100 times it's noticeable.

Rename this to `track2.wav` and add it to the `raw` folder where the `track.mp3` is already available. I just cut a little piece of the original `track.mp3`. It's a bit annoying, sorry :)
[track2.txt](https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/files/13969750/track2.txt)

Rename to `PlayerExample.cpp`
[PlayerExample.txt](https://github.com/superpoweredSDK/Low-Latency-Android-iOS-Linux-Windows-tvOS-macOS-Interactive-Audio-Platform/files/13969738/PlayerExample.txt)

Change the loaded file in the `MainActivity` to load the new `track2.wav` (line 35 in the MainActivity)

The last commit on my Superpowered project is `d67e895ca31e9d42fd41ba56e38ab970da243cab` (Version 2.6.2).

I hope I didn't miss anything or did something stupid what is causing this. I'm curious to see if you experience it as well.

**Comment by renezuidhof** [comment]
I'm guessing it might be because `loopBetween` uses milliseconds. So if an audiofile is 3000.3 milliseconds it will miss the 0.3 millisecond difference.

**Comment by gaborszanto** [comment]
This is a great find! I'll change the player API to return a double instead of unsigned int.

**Comment by renezuidhof** [comment]
That's great! Thanks
