### ISSUE TITLE
iOS How to open MPMediaItem audio File. (iTunes Audio file)?

### ISSUE THREAD

**Issue by abhimanyujindal10** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#14]
I am able to process/play audio file either from Bundle or from the document directory but not able to access the audio file of iTunes directly. Do I need to write the audio file first in document directory using audio export session first and then use the file for further process? If yes, It will take lot of processing to write and then further process to analyze the song.

**Comment by superpoweredSDK** [comment]
Yes, you need to use an export session first. If you use a passthrough export session preset, then it's just a file copy operation and it's not expensive.

**Comment by andresteves** [comment]
That still take a lot of time if you fetching them from the itunes library and copying them. I have a real-time app that fetch playlist from itunes and play them. Can you provide fast and not expensive code for that to happen? Otherwise my app will seem to stuck on itunes library while copying the whole playlist...

**Comment by superpoweredSDK** [comment]
The next version will support direct reading from the iPod library.
