### ISSUE TITLE
Example request

### ISSUE THREAD

**Issue by abmgames** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#15]
I will be grateful if you provide any example how to use  SuperpoweredEcho or reverb with offlineProcess in as you provide for SuperpoweredTimeStretching iOS

**Comment by superpoweredSDK** [comment]
There is no difference to the online examples - you just throw it's process() method into the right place.

For offline with a decoder, after you have the decoded samples from a decoder, and converted them to floating point using a mixer method, just process() and you're done. There is no need for the complex audio buffer list thing.

**Comment by abmgames** [comment]
Please help with few lines of code i'm stuck here :-))

**Comment by IonutNegru87** [comment]
Hello,

I'm also struggling with adding an bpm feature to one of our work in progress projects through your library.
I'm having trouble adding this feature and I couldn't find any relevant sample for this.
From what I've read, I should use <b>SuperpoweredOfflineAnalyzer</b> class, but I haven't had any success on integrating it.
Can you please provide some sample or guidelines for this.

Thank you.

**Comment by myrunrun** [comment]
I try it ,but failed.Please show me some light and sample codes!Thanks!

**Comment by myrunrun** [comment]
Have you sloved your problem? Please show me some light and sample codes!Thank you!^_^

**Comment by IonutNegru87** [comment]
Hello,

No, sadly I didn't, for now we dropped this feature because we couldn't
find the necessary support for implementing everything that we needed. If
you can provide more details for this, we will study them and maybe resume
this feature for our project.
Thank you.

Best regards,
Negru Ionut Valentin

**Comment by chintan100** [comment]
I've been struggling with saving a sound file with SuperpoweredEcho applied for 2 days now. 

And from the replies above, it seems a lot of other people are struggling as well. 

I asked the CTO of @superpoweredSDK on Twitter to see if he can provide some sample code since a lot of people are asking for but instead of 8-10 lines of sample code, i got 8-10 tweets from him explaining how i am asking him to do my job: https://twitter.com/FollowChintan/status/621262065261346816

They also seem to prefer closing github issues without really providing a solution so if anybody from above @abmgames @IonutNegru87 @myrunrun have found a solution to this, please let me know.

**Comment by iliaskarim** [comment]
@chintan100 the question was already answered--let me elaborate on it for you.

[See line 110 in the offline example `timeStretch->process(&inputBuffer, outputBuffers);`](https://github.com/superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine/blob/master/SuperpoweredOfflineProcessingExample/SuperpoweredOfflineProcessingExample/ViewController.mm#L110)

_All you need to do is replace `timeStretch` with an instance of whatever effect you want to apply, e.g. echo or reverb_

I'm afraid that Gábor is right that more sample code is not the solution. Best of luck with your implementation!

**Comment by chintan100** [comment]
Hi @iliaskarim , 
I already took a shot at that, but if you see, SuperpoweredEcho has different process() method since the parameters are different than timeStretch. However, after much struggle, i was able to find some success saving the results to file using the below method:

```
-(void)createSoundFileFromEffect:(SuperpoweredFX *)effect{

    SuperpoweredDecoder *decoder = new SuperpoweredDecoder(false);

    const char *openError = decoder->open([[self fullPathAtCache:@"record.wav"] fileSystemRepresentation], false, 0, 0);
    
    if (openError) {
        NSLog(@"%s", openError);
        delete decoder;
        return;
    };
    
    // Create the output WAVE file.    
    FILE *fd = createWAV([[self fullPathAtCache:@"recordingWithEffects.wav"] fileSystemRepresentation], decoder->samplerate, 2);
    
    if (!fd) {
        
        NSLog(@"File creation error.");
        delete decoder;
        return;
    };

    // Create a buffer for the 16-bit integer samples.
    short int *intBuffer = (short int *)malloc(decoder->samplesPerFrame * 2 * sizeof(short int) + 16384);
    
    while (true) {
        
        unsigned int samplesDecoded = decoder->samplesPerFrame;
        
        if (decoder->decode(intBuffer, &samplesDecoded) != SUPERPOWEREDDECODER_OK){
            
            break;
        }
        
        SuperpoweredShortIntToFloat(intBuffer, offlineBuffer, samplesDecoded);
        
        effect->process(offlineBuffer, offlineBuffer, samplesDecoded);
        
        SuperpoweredFloatToShortInt(offlineBuffer, intBuffer, samplesDecoded);
        
        // Write the audio to disk.
        fwrite(intBuffer, 1, samplesDecoded * 4, fd);
    }
    
    // Cleanup.
    closeWAV(fd);

    delete decoder;
    free(intBuffer);
}
```

The above method writes the file just fine but unlike the time stretch example (which i also have integrated in the code), when i try to play a sound with effect after a file has been created using the above method, the app crashes with ```EXC_BAD_ACCESS``` with the stack trace shown in image. 

Sometimes it crashes at line: 
```bool silence = !player->process(stereoBuffer, false, numberOfSamples, 1.0f, 0.0f, -1.0);``` in method:

```- (bool)audioProcessingCallback:(float **)buffers inputChannels:(unsigned int)inputChannels outputChannels:(unsigned int)outputChannels numberOfSamples:(unsigned int)numberOfSamples samplerate:(unsigned int)samplerate hostTime:(UInt64)hostTime```. 

Any hints about solving the crash issue after saving file will be great. Struggling with this for 2 days now.

**Comment by iliaskarim** [comment]
@chintan100 perhaps `offlineBuffer` is not allocated large enough? I don't see it in this method

I also don't see an image of a stack trace, nor do I see where you are calling `bool silence = !player->process(stereoBuffer, false, numberOfSamples, 1.0f, 0.0f, -1.0);`

The way that you are calling `process` on the effect looks good, though! I believe it should work provided your float buffer is adequately allocated

**Comment by chintan100** [comment]
@iliaskarim Sorry, forgot to attach image. Added image to above comment.

Here is the offlineBuffer being allocated elsewhere: 
```
// Allocating memory, aligned to 16.
    if (posix_memalign((void **)&offlineBuffer, 16, 4096 + 128) != 0){
        abort();
    }
```

Since the same size works for time stretch, i believe it should work for echo as well?

The ```bool silence = !player->process(stereoBuffer, false, numberOfSamples, 1.0f, 0.0f, -1.0);``` is called from within the delegate method:

```- (bool)audioProcessingCallback:(float **)buffers inputChannels:(unsigned int)inputChannels outputChannels:(unsigned int)outputChannels numberOfSamples:(unsigned int)numberOfSamples samplerate:(unsigned int)samplerate hostTime:(UInt64)hostTime```. 

The ```stereoBuffer``` also has the same allocation as ```offlineBuffer``` and it is working fine to save time stretch audio to file as shown in sample code provided with SDK.

**Comment by chintan100** [comment]
@iliaskarim Any more guidance you can give based on my last reply? :)

**Comment by iliaskarim** [comment]
@chintan100 I'm still not exactly sure what you mean `when i try to play a sound with effect after a file has been created using the above method, the app crashes with EXC_BAD_ACCESS` but perhaps you could post a link to a sample project on github that demonstrates your issue.

I also think it would help try to formulate your question into a stackoverflow post. Be sure to include hashtag #superpowered. I think stackoverflow may be a better venue than the project's github issues for questions like yours.

**Comment by ruchiragile** [comment]
@iliaskarim , there's no tag like #superpowered on SO. Someone with more reputation should create it first. 

Please have a look at this question
http://stackoverflow.com/questions/32667375/using-superpoweredsdk-in-ios

**Comment by ruchiragile** [comment]
`- (void)createSoundFileFromEffect:(SuperpoweredFX *)effect` @chintan100, Is this your implemented or given in examples from Superpowered?

**Comment by ruchiragile** [comment]
Can you guys help me with this?

What I'm doing is,

I've a mp3 file, on which I want to apply a filter (as given in Superpowered sample), once I apply, then I want to save it as new file? Is it possible? If yes, how?

I'm not found a way to accomplish this stuff.

Please help !!!! @superpoweredSDK @chintan100 @iliaskarim @abmgames @IonutNegru87

**Comment by ruchiragile** [comment]
@chintan100, should I declare offlineBuffer like this,

float *offlineBuffer ? 

Please let me know.

**Comment by chintan100** [comment]
@ruchiragile  Sorry, i don't have anything more to offer since i have stopped working on integrating @superpoweredSDK due to lack of proper documentation/support and my own limited C++ knowledge.
