### ISSUE TITLE
frequencyDomain->timeDomainToFrequencyDomain is called multiple times

### ISSUE THREAD

**Issue by nevosegal** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#176]
I am using a bufferSize of 512 but would like to run the FFT on buffers of 2048. I therefore concatenate buffers and call the `timeDomainToFrequencyDomain()` on the concatenated 2048-long buffer. I also set the `fftSize` to 2048. The output I get is that the function is called 4 times (in the while loop), instead of once. I am assuming that this happens because the system-wide buffer size is set to 512? 

Thanks.

**Comment by marafat** [comment]
Hi nevosegal, I have been working with Superpowered for some time on Android. I am assuming you are working on Android. There are few points that should be clarified here. If you want FFT to be called once every 2048 samples you should:
* make sure that the `maxOverlap` parameter used to initialize your `SuperpoweredFrequencyDomain` obj is set to `0`. You probably were seeing 4 callbacks because if you don't set this parameter it takes a default value of `4`.
* you don't have to concatenate buffers. The `SuperpoweredFrequencyDomain` obj does it for you internally as long as you are using `addInput()` to pass in new samples. 
* you don't need to set `fftSize` on the `SuperpoweredFrequencyDomain` obj. It is configured from the initializer's parameter `fftLogSize` where a value of 11 correspond to 2048 samples (2^11 = 2048).

Final note: I am not sure how flexible are you about the number `512`. keep in mind that your system should work regardless of the buffer size. In Android, the lowest audio latency is achieved by first asking the system for preferred sample rate and buffer size, and use those in your audio setup.

I hope you found that helpful.

**Comment by nevosegal** [comment]
Hi @marafat and thanks for the detailed response - very helpful indeed. I will try everything you suggested and report back if I have more issues. Another question I was wondering about and couldn't find an answer for in the documentation is regarding the output of the Superpowered FFT. So I see the output is the `magnitude` and `phase` of the left and the right channels. Are these the real and imaginary values of the FFT's complex output? Or is it the magnitude (`sqrt(real^2 + imaginary^2)`) and phase (`atan(imaginary/real)`)? I tried digging into the code but can't find the actual implementation. Thanks!

**Comment by nevosegal** [comment]
Oh - I now see  ([here](http://superpowered.com/docs/class_superpowered_frequency_domain.html#acaa7401c8fff4f9e4d0b2c316c15df8f)) that the `complexMode` boolean returns the real and imaginary part of the complex output. So the default must be the magintude and phase response as described above. Thanks again.

**Comment by superpoweredSDK** [comment]
Exactly as marafat said. SuperpoweredFrequencyDomain does overlapping and buffering for you.

**Comment by marafat** [comment]
One thing I forgot to mention is that you need to call `frequencyDomain->advance(frequencyDomain->fftSize);` before you exit "the while loop"..

**Comment by nevosegal** [comment]
Doesn't it automatically advance `fftSize` samples? Do I need to explicitly pass this parameter?

**Comment by marafat** [comment]
I found from experience that if you don't pass a parameter to `advance()` you will get an FFT result with every input buffer.

**Comment by nevosegal** [comment]
Thanks @marafat, I appreciate it. @superpoweredSDK can you maybe confirm/explain?

**Comment by nevosegal** [comment]
@marafat - you are right. Thanks.
