### ISSUE TITLE
How to use superpowered to recognize a series of DTMF signals

### ISSUE THREAD

**Issue by jinyichao** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#193]
Good day!

I have a question of using superpowered SDK to recognize DTMF signals. In particular, I am trying to use SuperpoweredBandpassFilterbank to detect frequency magnitudes, and get two strongest frequencies as the DTMF signals. 

The problem is that, for any single DTMF signal, it works very well. But it does not work well for a series of DTMF signals. For example, 27, the frequencies for 2 are 697Hz and 1336Hz, and 7 are 852Hz and 1209Hz. However, my code will sometimes wrongly recognize 27 into 18, where 1 consists 697Hz and 1209 Hz, 8 consists 852Hz and 1336Hz.  

I doubt the problem might be caused by the inner logic of SuperpoweredBandpassFilterbank, which takes the sample data in overlapped windows. As a result, it mixes the frequencies from two successive DTMF signals. Could you please kindly confirm or explain it, and give your suggestions on how to recognize a series of DTMF signals by using superpoweredSDK. 

Thank you!

**Comment by superpoweredSDK** [comment]
Yes, if you continuously run the SuperpoweredBandpassFilterbank and read the result at the very end, you will get the overall, mixed frequency response.
Instead of using the filter bank's process() method, use the processNoAdd() method, cumulate the results in bands with your own code and periodically read+reset them.
