### ISSUE TITLE
Integration with audiobus sdk on IOS

### ISSUE THREAD

**Issue by rene-dohan** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#2]
http://audiob.us you should support this to be relevant for IOS development...

**Comment by odbol** [comment]
@rene-dohan did you ever get this working with Audiobus? Would love to see an example...

**Comment by plasmaphonic** [comment]
There’s nothing like a good simple ground up Example to get people to start using the code.

It’d be nice if there’s a iOS Swift Example.

**Comment by superpoweredSDK** [comment]
@plasmaphonic There is an iOS Swift example in the SDK, in the SuperpoweredFrequencies folder.

**Comment by juhoj** [comment]
Would be really great to hear if anyone succeeded in using Superpowered with Audiobus and was there any complications. Also I too would enjoy some sample code. It's just so essential to iOS music app development that it would benefit Superpowered a lot to have examples of this. I'm replying here because this is basically the only reference on using Audiobus with Superpowered...
