### ISSUE TITLE
calling methods on an instance of SuperpoweredAdvancedAudioPlayer from its callback

### ISSUE THREAD

**Issue by palad1** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#200]
I would like to reset the player when it reaches EOF  - I don't want to loop, in effect I want to insert a given number of silence samples between each loop.

I have several questions for this use-case:

1. In which thread is the player's callback fired? The audio thread? The IO thread? the same thread that called process() ? 
2. Is it safe to call `player.setPosition(0,false,false)` from the player callback? Will this create stutter?
3. When is the best time to call player.cachePosition(0,'a') (so I can seek to start without triggering IO)

This is unrelated to the previous crash issue I just raised.

Alternately, if you have a better solution (without using track BPM) to add a given number of silence frames between each loops, I would love to hear it!

Thanks.

**Comment by superpoweredSDK** [comment]
1. Depends on the event. EOF may be called from the audio thread (which is the same thread that called process() usually). But from any other thread too, that's why you shouldn't do anything blocking or expensive in the callback.

2. Yes.

3. As soon as possible, so the player has time to cache.

Adding silence frames between loops can be done with not calling the player's process() method and putting silence into the audio buffer instead.
