### ISSUE TITLE
Can't read audio files from assets

### ISSUE THREAD

**Issue by pabitrapadhy** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#261]
Hello,

Using SuperpoweredAdvancedAudioPlayer::Open()
we are able to read files and play it from external location, like filepath
e.g. data/xyz/etc.mp3

but we are not able to open an audio file present inside - 
assets/
in android file system.
So, if I give, ::open("assets/Sounds/abc.mp3"), it gives us load error.

As most of the cross-compiling applications read files from the assets or sub-folders inside assets,
Could this be fixed in the next update please ?

**Comment by superpoweredSDK** [comment]
Android assets are compressed inside the apk file, not directly accessible. Since mp3 files can not be compressed further, putting them into "normal" assets is not a good choice.

assets/raw is the only place where assets are not compressed. The cross example project shows how to handle files there.
