### ISSUE TITLE
More static and a suggestion

### ISSUE THREAD

**Issue by svenoaks** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#298]
I recently got an S8 Plus with Android 7.0, and app using SuperpoweredAndroidIO is full of static/dropouts, even with just CrossExample. SuperpoweredCPU did not fix it. What fixed it almost entirely is set

`SLDataLocator_AndroidSimpleBufferQueue outputLocator = { SL_DATALOCATOR_ANDROIDSIMPLEBUFFERQUEUE, 2 };`

For double buffering. This doesn't do anything on some versions of Android, they keep breaking it - https://issuetracker.google.com/issues/37133526 and https://youtu.be/dAyeEN21FbM?t=7m3s but I believe it will fix many devices that have static. It also can be done for the input I believe.

Google recommends to always double buffer - https://youtu.be/dAyeEN21FbM

**Comment by svenoaks** [comment]
Note: to make it truly dropout free on the S8 Plus I had to use SuperpoweredCPU (at least turning it on when the screen is turned off) as well as the double buffering above, otherwise it would still have dropouts when the phone is locked.

**Comment by svenoaks** [comment]
He talks about the changes to Nougat that makes less buffers for OpenSL fast mixer as compared to Marshmallow and here recommends the double buffer as well: https://youtu.be/dAyeEN21FbM?t=7m36s

**Comment by superpoweredSDK** [comment]
Which Android version is this exactly? Some 7.1.1 builds are having a huge CPU core handling bug, preventing proper scheduling of audio threads and CPU sets are chaotic too.

**Comment by svenoaks** [comment]
It's on Android 7.0. Sad to see that android still hasn't figured out how to play audio yet. Nexus 9 with 7.1.1 has static too even with the superpoweredCPU and double buffer.

**Comment by svenoaks** [comment]
On a related note do you think it is worth it for Superpowered to use Samsung Pro Audio on the devices that support it and only fallback to OpenSL since it seems to have so many problems or is that also problematic?

**Comment by superpoweredSDK** [comment]
Samsung Professional Audio SDK needs you to totally re-structure your program, as the audio part of it will run in a separate process and you need to use special inter-process APIs to communicate.

Regarding the Android bug, it's here: https://issuetracker.google.com/issues/37324116
There is no workaround or fix for 7.1.1. That version is just "doesn't work".

**Comment by svenoaks** [comment]
Just so you know if Cross DJ is your app, there is tons of static in that app as well on S8 Plus, even in the foreground

**Comment by romanbsd** [comment]
@svenoaks I used SAPA instead of SuperpoweredAndroidIO in our app, and it kinda worked. But I believe that the only device that could benefit from it in our case (low latency), it's S6. And I'm not even sure it's still relevant, since Samsung released Nougat for S6. Its greatest problem in our case is that it requires your app to be 32-bit, as they don't have 64-bit binaries. The control flow is a bit awkward, too.

Regarding the buffers -  I think that the best result I had was with SLDataLocator_AndroidSimpleBufferQueue outputLocator = { SL_DATALOCATOR_ANDROIDSIMPLEBUFFERQUEUE, 2 };
and setting latencySamples to bufferSize.

Most examples you can find on the internet set SL_DATALOCATOR_ANDROIDSIMPLEBUFFERQUEUE to 2 or more.

**Comment by svenoaks** [comment]
I don't think didn't using more than one ANDROIDSIMPLEBUFFERQUEUE did anything in versions of Android before Nougat, Google guy says it did nothing in Marshmallow in talk above, and I read that before. Perhaps in 4.1 and 4.2 it worked, but 4.3 - 6.0 it was useless is my best guess.
