### ISSUE TITLE
Audio files mixing incomprehension

### ISSUE THREAD

**Issue by VyacheslavVladimirovich** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#31]
Does it only one way to mixing two or more audio files using synchronized SuperpoweredAdvancedAudioPlayers? And how should i set offset from start of composition for audio files? As i understand for multi-track system with ability of mixing samples in one track i should create player for every different sample. Can it cause a problem if i have more than hundred different samples. So now i see possibility  to use this great SDK for creating DJ app but can't understand how can i clearly use it for multi-track mixer. thx

**Comment by superpoweredSDK** [comment]
You can create your own players if you like, Superpowered is very open. Using setPosition you can jump to any part of the track. A multi-track system doesn't play hundreds of different samples in the same time, but if you are going to play like 16 or 32, you need to implement your own players playing from memory, because none of the existing player solutions will work for you.

**Comment by VyacheslavVladimirovich** [comment]
Thanks for the answer.
