### ISSUE TITLE
Website home's list of users has useless links

### ISSUE THREAD

**Issue by 0joshuaolson1** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#318]
They link to http://superpowered.com/#, instead of not being links or linking to evidence that the list is actual Superpowered users.

**Comment by superpoweredSDK** [comment]
Since this is not an issue with the SDK, i close this ticket now.
Superpowered users have to include the Superpowered logo or similar reference in their apps or app description. You can check the app descriptions in their app stores, or download those apps and check Superpowered mentioned in typically a settings screen or splash screen.

**Comment by 0joshuaolson1** [comment]
You do not have a repo for the website, so there is no better place to track it. You also did not address the issue. Why are there links that don't work?
