### ISSUE TITLE
Which parts could be open sourced?

### ISSUE THREAD

**Issue by 0joshuaolson1** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#338]
I understand the desire for business flexibility later, but are there any parts that could be opened to scrutiny?
- to find bugs
- to verify the claim of a 'six-pole filter'
- etc.

**Comment by superpoweredSDK** [comment]
Superpowered is based on patented technology. It significantly outperforms every other audio DSP technology, including Core Audio. We're not able to reveal the core IP, which would be irresponsible towards our investors as well. 
The audio I/O classes are open source. We could open-source some minimal additional parts only, not really helping with anything useful. 
Yes, open-source could help finding bugs, but since Superpowered is used in millions and millions of installs, we receive tons of crash reports and fix them regularly.

**Comment by 0joshuaolson1** [comment]
All right. Note for other readers: some *Android* audio I/O is open source.

**Comment by superpoweredSDK** [comment]
iOS, Mac OSX and Linux audio I/O code, Unity integration are open source too.

**Comment by 0joshuaolson1** [comment]
In this repo, I see examples and wrapper-only headers. What did I miss?

**Comment by superpoweredSDK** [comment]
The SDK consists of fully working example projects, headers for the SDK and the static library itself.

**Comment by 0joshuaolson1** [comment]
Again, what open source parts? Besides what I mentioned, I only see SuperpoweredNBandEQ.cpp

**Comment by superpoweredSDK** [comment]
The open source parts mentioned in this conversation:

- Audio I/O code for Android, iOS, tvOS, Mac OSX and Linux.
- Unity integration.
- N-band eq.

**Comment by 0joshuaolson1** [comment]
Using tvOS as an example, I only see example code, not any parts of its Super Powered implementation.

I don't consider wrapper-only headers open sourced parts of the SDK, hence why I clarified for other readers that basically just some Android stuff is open.
