### ISSUE TITLE
Pitch Shifting sound quality very poor

### ISSUE THREAD

**Issue by DanNi0130** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#420]
The sound quality degrades very quickly when changing the pitch, I noticed a couple of older issues that referenced this #213 and #126 is this something that is actively being worked on?

**Comment by superpoweredSDK** [comment]
We have no plans for working on this.

**Comment by DanNi0130** [comment]
Is there an alternative way of time stretching after set tempo so that doesn't have the sort of vocoder phasing effect?

**Comment by DanNi0130** [comment]
Would it be possible to use SuperpoweredResampler to throw away enough samples to speed up the audio?

**Comment by superpoweredSDK** [comment]
Perhaps you were looking for the wrong Superpowered feature at first. Let me explain:

- time stretching: change tempo without changing the pitch
- pitch shifting: change pitch without changing the tempo
- resampling: change tempo and pitch together

That's why there is not continuous pitch shifter. You are looking for the resampler for a smooth "turntable-like" simulation.
