### ISSUE TITLE
Support for Cordova and React Native?

### ISSUE THREAD

**Issue by jamesharvey2** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#421]
Hello SuperpoweredSDK, 

Is it possible for you guys to make this package work for React Native and Apache Cordova using javascript? 
We would greatly appreciate that. 
https://facebook.github.io/react-native/
https://cordova.apache.org

**Comment by CodeJd** [comment]
For react native you have this:
https://github.com/MathieuDebit/react-native-superpowered

**Comment by jamesharvey2** [comment]
@CodeJd  Wow! that's amazing! is it perfect implementation for react native? I want to try it for sure... and I would still like to see an official react native and cordova version of Superpowered SDK triggered by javascript or typescript.

**Comment by superpoweredSDK** [comment]
This will unlikely to happen, because low latency, real-time and high performance data processing can not be done in upper level frameworks.

Superpowered directly reveals all data connections/memory buffers, so it's very open, and easy to do sophisticated custom processing.This is only possible in C/C++ (and Objective-C++ at Apple).

Full upper level support would only possible with complex and abstract connection/graph management. That's why you can't do sophisticated custom things with Core Audio/AVAudioEngine and Swift for example.

The best compromise is to write all the high performance code in the truly native layer, then bridge it to your high level framework. Identically to the framework suggested by CodeJd.

**Comment by jamesharvey2** [comment]
> The best compromise is to write all the high performance code in the truly native layer, then bridge it to your high level framework. Identically to the framework suggested by CodeJd.

Yes, this is the only solution... basically it needs a bridge that can trigger functions & features of Superpowered SDK by using TypeScript / Javascript from upper level (React Native). 

I would like to program this myself when I learn more about architecture of superpowered SDK....
