### ISSUE TITLE
Needs more example for offline processing

### ISSUE THREAD

**Issue by myrunrun** [superpoweredSDK/Low-Latency-Android-Audio-iOS-Audio-Engine#43]
I will be grateful if you can provide any  audio effect example for offlineProcess.And I want it to be saved as MP3.Please show me some light and sample codes!Thank you!^_^ @superpoweredSDK

**Comment by chintan100** [comment]
@superpoweredSDK Is it possible to provide some sample code for above requested feature where we can save the FX output to a WAV file? 

I want to apply an FX effect to a recorded sound file and save the new sound file with FX. I can apply the effect and play the sound as sample code is available for that but due to lack of sample code i am not able to figure out how to save the FX file.

I am struggling with it as well and could not set it up correctly after one full day of working on just this.
